import { useEffect, useState } from "react";
import { Alert, Button, Card, CardContent, Grid, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";
import { getAdminJobs, getAdminResumes, getAdminStats, getAdminUsers, syncAdminJobs, type AdminJob, type AdminResume, type AdminStats, type AdminUser } from "../api/adminApi";

export default function AdminDashboard() {
  const [stats, setStats] = useState<AdminStats | null>(null); const [users, setUsers] = useState<AdminUser[]>([]); const [resumes, setResumes] = useState<AdminResume[]>([]); const [jobs, setJobs] = useState<AdminJob[]>([]); const [status, setStatus] = useState<"ACTIVE" | "INACTIVE">("ACTIVE"); const [message, setMessage] = useState("");
  const load = async () => { const [nextStats, nextUsers, nextResumes, nextJobs] = await Promise.all([getAdminStats(), getAdminUsers(), getAdminResumes(), getAdminJobs(status)]); setStats(nextStats); setUsers(nextUsers); setResumes(nextResumes); setJobs(nextJobs); };
  useEffect(() => { void load().catch(() => setMessage("Could not load administrator data.")); }, [status]);
  const sync = async () => { setMessage("Synchronizing jobs..."); try { const result = await syncAdminJobs(); setMessage(result.message ?? `Synchronization completed: ${result.new_jobs ?? 0} new jobs.`); await load(); } catch { setMessage("Job synchronization failed."); } };
  return <Stack spacing={3}><Stack direction="row" sx={{ justifyContent: "space-between", alignItems: "center" }}><div><Typography variant="h4" sx={{ fontWeight: 700 }}>Admin Dashboard</Typography><Typography color="text.secondary">System overview and management</Typography></div><Button variant="contained" onClick={() => void sync()}>Sync jobs</Button></Stack>{message && <Alert severity="info">{message}</Alert>}<Grid container spacing={2}>{[["Total jobs", stats?.jobs ?? "—"],["Active jobs", stats?.active_jobs ?? "—"],["Inactive jobs", stats?.inactive_jobs ?? "—"],["Last synchronization", stats?.last_synchronization ? new Date(stats.last_synchronization).toLocaleString() : "Never"]].map(([label, value]) => <Grid key={label} size={{ xs: 12, sm: 6, md: 3 }}><Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant={label === "Last synchronization" ? "body1" : "h4"}>{value}</Typography></CardContent></Card></Grid>)}</Grid><Stack direction="row" spacing={1}><Button variant={status === "ACTIVE" ? "contained" : "outlined"} onClick={() => setStatus("ACTIVE")}>Active jobs</Button><Button variant={status === "INACTIVE" ? "contained" : "outlined"} onClick={() => setStatus("INACTIVE")}>Inactive jobs</Button></Stack><DataTable title={`${status} jobs`} headers={["Title", "Company", "Location", "Status", "Inactive since"]} rows={jobs.map(job => [job.title, job.company, job.location, job.status, job.inactive_at ? new Date(job.inactive_at).toLocaleString() : "—"])} /><DataTable title="Users" headers={["Name", "Email", "Role", "Status"]} rows={users.map(user => [user.full_name, user.email, user.role.toUpperCase(), user.is_active ? "Active" : "Inactive"])} /><DataTable title="Uploaded resumes" headers={["Filename", "User", "Uploaded"]} rows={resumes.map(resume => [resume.filename, resume.user_email, new Date(resume.uploaded_at).toLocaleString()])} /></Stack>;
}
function DataTable({ title, headers, rows }: { title: string; headers: string[]; rows: string[][] }) { return <Card><CardContent><Typography variant="h6" sx={{ mb: 1 }}>{title}</Typography><Table size="small"><TableHead><TableRow>{headers.map(header => <TableCell key={header}>{header}</TableCell>)}</TableRow></TableHead><TableBody>{rows.slice(0, 100).map((row, index) => <TableRow key={index}>{row.map((cell, cellIndex) => <TableCell key={cellIndex}>{cell}</TableCell>)}</TableRow>)}</TableBody></Table></CardContent></Card>; }
