import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { Alert, Button, Card, CardContent, Grid, Stack, Tab, Tabs, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { getAdminAudit, getAdminCompanies, getAdminJobs, getAdminStats, getAdminUsers, syncAdminJobs, updateAdminJob, updateAdminUser, type AdminJob, type AdminStats, type AdminUser } from "../api/adminApi";

export default function AdminDashboard() {
    const [tab, setTab] = useState(0); const [stats, setStats] = useState<AdminStats | null>(null); const [users, setUsers] = useState<AdminUser[]>([]); const [jobs, setJobs] = useState<AdminJob[]>([]); const [companies, setCompanies] = useState<{ id: number; name: string; industry: string | null; hiring_status: string | null; is_active: boolean }[]>([]); const [audit, setAudit] = useState<{ id: number; action: string; resource: string; detail: string | null; created_at: string }[]>([]); const [status, setStatus] = useState<"ACTIVE" | "INACTIVE">("ACTIVE"); const [search, setSearch] = useState(""); const [message, setMessage] = useState("");
    const load = async () => { const [nextStats, nextUsers, nextJobs, nextCompanies, nextAudit] = await Promise.all([getAdminStats(), getAdminUsers(), getAdminJobs(status), getAdminCompanies(search), getAdminAudit()]); setStats(nextStats); setUsers(nextUsers); setJobs(nextJobs); setCompanies(nextCompanies.items); setAudit(nextAudit.items); };
    useEffect(() => { void load().catch(() => setMessage("Could not load administrator data.")); }, [status]);
    const sync = async () => { setMessage("Synchronizing jobs..."); try { const result = await syncAdminJobs(); setMessage(result.message ?? `Synchronization completed: ${result.new_jobs ?? 0} new jobs.`); await load(); } catch { setMessage("Job synchronization failed."); } };
    const toggleUser = async (user: AdminUser) => { try { await updateAdminUser(user.id, { is_active: !user.is_active }); await load(); } catch { setMessage("User update failed."); } };
    const toggleJob = async (job: AdminJob) => { try { await updateAdminJob(job.id, { status: job.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" }); await load(); } catch { setMessage("Job update failed."); } };
    return <Stack spacing={3}><Stack direction={{ xs: "column", sm: "row" }} sx={{ justifyContent: "space-between", alignItems: { sm: "center" }, gap: 2 }}><BoxTitle /><Button variant="contained" onClick={() => void sync()}>Sync jobs</Button></Stack>{message && <Alert severity="info">{message}</Alert>}<Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable"><Tab label="Overview" /><Tab label="Users" /><Tab label="Companies" /><Tab label="Jobs" /><Tab label="Audit log" /></Tabs>{tab === 0 && <Overview stats={stats} />}{tab === 1 && <Card><CardContent><Stack direction={{ xs: "column", sm: "row" }} sx={{ justifyContent: "space-between", gap: 2, mb: 2 }}><Typography variant="h6">User management</Typography><TextField size="small" label="Search users" value={search} onChange={event => setSearch(event.target.value)} onKeyDown={event => { if (event.key === "Enter") void load(); }} /></Stack><DataTable headers={["Name", "Email", "Role", "Status", "Action"]} rows={users.map(user => [user.full_name, user.email, user.role.toUpperCase(), user.is_active ? "Active" : "Inactive", <Button key={user.id} size="small" onClick={() => void toggleUser(user)}>{user.is_active ? "Deactivate" : "Activate"}</Button>])} /></CardContent></Card>}{tab === 2 && <Card><CardContent><Typography variant="h6" sx={{ mb: 2 }}>Company management</Typography><DataTable headers={["Name", "Industry", "Hiring status", "Status"]} rows={companies.map(company => [company.name, company.industry ?? "—", company.hiring_status ?? "—", company.is_active ? "Active" : "Inactive"])} /></CardContent></Card>}{tab === 3 && <Card><CardContent><Stack direction="row" spacing={1} sx={{ mb: 2 }}><Button variant={status === "ACTIVE" ? "contained" : "outlined"} onClick={() => setStatus("ACTIVE")}>Active jobs</Button><Button variant={status === "INACTIVE" ? "contained" : "outlined"} onClick={() => setStatus("INACTIVE")}>Inactive jobs</Button></Stack><DataTable headers={["Title", "Company", "Location", "Status", "Action"]} rows={jobs.map(job => [job.title, job.company, job.location, job.status, <Button key={job.id} size="small" onClick={() => void toggleJob(job)}>{job.status === "ACTIVE" ? "Deactivate" : "Activate"}</Button>])} /></CardContent></Card>}{tab === 4 && <Card><CardContent><Typography variant="h6" sx={{ mb: 2 }}>Admin audit log</Typography><DataTable headers={["Action", "Resource", "Detail", "Timestamp"]} rows={audit.map(item => [item.action, `${item.resource} #${item.id}`, item.detail ?? "—", new Date(item.created_at).toLocaleString()])} /></CardContent></Card>}</Stack>;
}

function BoxTitle() { return <div><Typography variant="h4" sx={{ fontWeight: 700 }}>Admin Dashboard</Typography><Typography color="text.secondary">Secure system management and operational oversight</Typography></div>; }
function Overview({ stats }: { stats: AdminStats | null }) { const cards: [string, string | number][] = [["Users", stats?.users ?? "—"], ["Active users", stats?.active_users ?? "—"], ["Companies", stats?.companies ?? "—"], ["Startups", stats?.startups ?? "—"], ["Jobs", stats?.jobs ?? "—"], ["Applications", stats?.applications ?? "—"], ["Target companies", stats?.target_companies ?? "—"], ["Uploaded resumes", stats?.resumes ?? "—"], ["Mock interviews", stats?.mock_interviews ?? "—"], ["Learning completions", stats?.learning_progress ?? "—"]]; return <><Grid container spacing={2}>{cards.map(([label, value]) => <Grid key={label} size={{ xs: 6, sm: 4, md: 2.4 }}><Card><CardContent><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h5" sx={{ mt: 1, fontWeight: 700 }}>{value}</Typography></CardContent></Card></Grid>)}</Grid><Grid container spacing={2}><Grid size={{ xs: 12, md: 6 }}><Card><CardContent><Typography variant="h6">Most applied companies</Typography>{(stats?.most_applied_companies ?? []).map(item => <Typography key={item.name} sx={{ mt: 1 }}>{item.name} · {item.count}</Typography>)}</CardContent></Card></Grid><Grid size={{ xs: 12, md: 6 }}><Card><CardContent><Typography variant="h6">Popular roles</Typography>{(stats?.most_popular_roles ?? []).map(item => <Typography key={item.name} sx={{ mt: 1 }}>{item.name} · {item.count}</Typography>)}</CardContent></Card></Grid></Grid></>; }
function DataTable({ headers, rows }: { headers: string[]; rows: (string | number | ReactNode)[][] }) { return <Table size="small"><TableHead><TableRow>{headers.map(header => <TableCell key={header}>{header}</TableCell>)}</TableRow></TableHead><TableBody>{rows.slice(0, 100).map((row, index) => <TableRow key={index}>{row.map((cell, cellIndex) => <TableCell key={cellIndex}>{cell}</TableCell>)}</TableRow>)}</TableBody></Table>; }
