import { useEffect, useState } from "react";
import { Alert, Box, Button, Container, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Snackbar, Stack, Step, StepLabel, Stepper, TextField, Typography } from "@mui/material";
import applicationService from "../services/applicationService";
const fallbackStages = ["Applied", "In Progress", "Shortlisted", "Interview", "Offer", "Accepted", "Rejected", "Withdrawn"];
type Application = { id: number; company: string; job_title: string; location?: string; status: string; source_type: string; notes?: string; rounds?: Array<{ round_number: number; title: string }> };
export default function ApplicationTracker() {
  const [applications, setApplications] = useState<Application[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState<number | null>(null); const [open, setOpen] = useState(false); const [form, setForm] = useState({ company_name: "", job_title: "", location: "", job_url: "", notes: "", status: "Applied" });
  const load = async () => { try { setApplications(await applicationService.getApplications()); } catch { setError("Unable to load applications."); } };
  useEffect(() => { void load(); }, []);
  const update = async (app: Application, status: string) => { setSaving(app.id); setError(""); try { await applicationService.updateApplication(app.id, status); await load(); setNotice("Application stage saved."); } catch { setError("Could not save the application stage."); } finally { setSaving(null); } };
  const addCustom = async () => { try { await applicationService.createCustomApplication(form); setOpen(false); setForm({ company_name: "", job_title: "", location: "", job_url: "", notes: "", status: "Applied" }); await load(); setNotice("Custom application added."); } catch { setError("Could not add the custom application."); } };
  return <Container maxWidth="lg" sx={{ py: 4 }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" spacing={2} sx={{ mb: 3 }}><Box><Typography variant="h4" fontWeight={700}>Application Progress</Typography><Typography color="text.secondary">Company-specific rounds are loaded from verified database records.</Typography></Box><Button variant="contained" onClick={() => setOpen(true)}>Add custom application</Button></Stack>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Stack spacing={2}>{applications.map(app => { const stages = app.rounds?.length ? ["Applied", ...app.rounds.map(round => round.title)] : fallbackStages; const active = stages.indexOf(app.status); const failed = ["Rejected", "Withdrawn"].includes(app.status); return <Paper key={app.id} sx={{ p: 3 }}><Typography variant="h6">{app.job_title}</Typography><Typography color="text.secondary">{app.company}{app.location ? ` · ${app.location}` : ""} · {app.source_type}</Typography><Box sx={{ overflowX: "auto", py: 2 }}><Stepper activeStep={failed ? -1 : Math.max(active, 0)} alternativeLabel>{stages.map(stage => <Step key={stage}><StepLabel error={failed}>{stage}</StepLabel></Step>)}</Stepper></Box><TextField select size="small" label="Current status" value={app.status} disabled={saving === app.id} onChange={event => void update(app, event.target.value)}>{stages.map(stage => <MenuItem key={stage} value={stage}>{stage}</MenuItem>)}</TextField>{!app.rounds?.length && <Typography variant="caption" display="block" sx={{ mt: 1 }} color="text.secondary">Company-specific rounds: Not Available</Typography>}</Paper>; })}</Stack>{applications.length === 0 && <Paper sx={{ p: 4, textAlign: "center" }}><Typography>No applications yet. Track a scraped job or add one manually.</Typography></Paper>}<Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Add custom application</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField required label="Company" value={form.company_name} onChange={e => setForm({ ...form, company_name: e.target.value })} /><TextField required label="Job title" value={form.job_title} onChange={e => setForm({ ...form, job_title: e.target.value })} /><TextField label="Location" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /><TextField label="Job URL" value={form.job_url} onChange={e => setForm({ ...form, job_url: e.target.value })} /><TextField label="Notes" multiline minRows={2} value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" disabled={!form.company_name.trim() || !form.job_title.trim()} onClick={() => void addCustom()}>Add</Button></DialogActions></Dialog><Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={() => setNotice("")} message={notice} /></Container>;
}
