import { useState } from "react";
import { Alert, Box, Button, CircularProgress, IconButton, InputAdornment, Link, Paper, Snackbar, TextField, Typography } from "@mui/material";
import { Visibility, VisibilityOff } from "@mui/icons-material";
import { Link as RouterLink, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";

export default function Login() {
  const { login } = useAuth(); const nav = useNavigate(); const location = useLocation(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const successMessage = (location.state as { message?: string } | null)?.message;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { await login(email, password); const raw = localStorage.getItem("auth"); const role = raw ? (JSON.parse(raw) as { user: { role: "admin" | "user" } }).user.role : "user"; nav(role === "admin" ? "/admin" : ((location.state as { from?: { pathname: string } })?.from?.pathname ?? "/")); } catch { setError("Invalid email or password."); } finally { setLoading(false); } };
  return <Box sx={{ minHeight: "100vh", display: "grid", placeItems: "center", p: 2, bgcolor: "background.default" }}><Paper component="form" onSubmit={submit} sx={{ p: { xs: 3, sm: 4 }, width: "100%", maxWidth: 440, borderRadius: 3, boxShadow: 5 }}>{successMessage && <Alert severity="success" sx={{ mb: 2 }}>{successMessage}</Alert>}<Typography variant="h4" sx={{ fontWeight: 700 }}>Welcome back</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Sign in to continue building your career plan.</Typography><TextField margin="normal" label="Email" type="email" fullWidth required autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} /><TextField margin="normal" label="Password" type={showPassword ? "text" : "password"} fullWidth required autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} slotProps={{ input: { endAdornment: <InputAdornment position="end"><IconButton aria-label={showPassword ? "Hide password" : "Show password"} aria-pressed={showPassword} onClick={() => setShowPassword(value => !value)} onMouseDown={event => event.preventDefault()} edge="end">{showPassword ? <VisibilityOff /> : <Visibility />}</IconButton></InputAdornment> } }} /><Button type="submit" fullWidth variant="contained" disabled={loading} sx={{ mt: 2, py: 1.2 }}>{loading ? <CircularProgress size={24} color="inherit" /> : "Login"}</Button><Box sx={{ display: "flex", justifyContent: "space-between", mt: 2 }}><Link component={RouterLink} to="/forgot-password">Forgot password?</Link><Link component={RouterLink} to="/register">Create account</Link></Box></Paper><Snackbar open={Boolean(error)} autoHideDuration={6000} onClose={() => setError("")}><Alert severity="error" onClose={() => setError("")}>{error}</Alert></Snackbar></Box>;
}
